[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Recursos digitales basicos para migrantes 01"
authors = [{name = "Motri", email = "motri.instrumentales@gmail.com"}]
dynamic = ["version", "description"]
